<a href="https://colab.research.google.com/github/lsuhpchelp/lbrnloniworkshop2021/blob/master/day4/numpy_warmup_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
import numpy as np

# Warm-up Exercise for Numpy (Solution)

#### Create a 1D array of numbers from 0 to 9

- Desired output:

> `[0 1 2 3 4 5 6 7 8 9]`

In [ ]:
arr = np.arange(10)
print(arr)

#### Convert the above 1D array to a 2D array with 2 rows

- Desired output:

```
[[0 1 2 3 4]
 [5 6 7 8 9]]
 ```

In [ ]:
arr = arr.reshape(2,-1)
print(arr)

#### Calculate the square of a 1D vector, then reshape it to a column vector

- Desired output:

```
[0 1 2 3 4]
[ 0  1  4  9 16]
[[ 0]
 [ 1]
 [ 4]
 [ 9]
 [16]]
 ```

In [ ]:
a = np.arange(5)
print(a)
a2 = a**2
print(a2)
a2 = a2.reshape(-1,1)
print(a2)

#### Suppose in an experiment, there are two variables x (from 1 to 5) and y (from 2 to 4), using numpy's broadcasting to calculate the matrix of all combinations of `x^2 + y` 

- Desired output:

```
[[ 3  4  5]
 [ 6  7  8]
 [11 12 13]
 [18 19 20]
 [27 28 29]]
 ```

In [ ]:
x = np.arange(1,6).reshape(-1,1)
print(x)
y = np.arange(2,5)
print(y)
z = x**2 + y
print(z)

#### Sum the rows and columns of the above matrix using Numpy's aggregation function

- Desired output:

```
[65 70 75]
[12 21 36 57 84]
```

In [ ]:
row_sum = z.sum(axis=0)
print(row_sum)
col_sum = z.sum(axis=1)
print(col_sum)

#### In Numpy, matrix multiplication is done using the dot() function, verify the matrix multiplication result by writing for loops:

Hint: (you only need to complete the below equation in the nested for loop)

$$cc_{i,j} =\sum_{k=1}^{nca} a_{i,k}b_{k,j} $$

For Matrix multiplication, you can refer to the wiki link to recall the basics:

https://en.wikipedia.org/wiki/Matrix_multiplication#Definition

- Desired output:

```
a=
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b=
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Using numpy's dot function: c=
 [[ 60  70]
 [160 195]]
Verified results using for loop: cc=
 [[ 60  70]
 [160 195]]
 ```

In [ ]:
nra = 2
nca = 5
ncb = 2
a = np.arange(nra*nca).reshape(nra,-1)
b = np.arange(nra*nca).reshape(-1,ncb)
print("a=\n",a)
print("b=\n",b)
c = a.dot(b)
print("Using numpy's dot function: c=\n",c)
cc = np.zeros_like(c)

# complete the vanilla version of matrix multiplication using for loop below:
for i in np.arange(nra):
    for j in np.arange(ncb):
        cc[i,j] = 0
        for k in np.arange(nca):
            cc[i,j] += a[i,k]*b[k,j]
print("Verified results using for loop: cc=\n",cc)

#### Calculate the min, max and mean brain weight and body weight of a dataset

In the demo notebook, we loaded the data from "data.txt" into a numpy array a, The 3 data columns include:
1.  the index,
1.  the brain weight;
1. the body weight.

Index 1-5 (row 1-5) are training set, index 6-9 (row 6-9) are test set

Calculate 

1. min, max and mean brain weight for training set 

2. min, max and mean body weight for test set 


Note that you should not use a for loop to complete this.

In [ ]:
# download the file to local virtual machine
! if [ ! -f "data.txt" ]; then wget 'https://raw.githubusercontent.com/lsuhpchelp/lbrnloniworkshop2019/master/day2_python/data.txt'; else echo 'file exists'; fi;
! cat data.txt # uncomment if you want to take a look at the data
txtfile = 'data.txt'
a = np.loadtxt(txtfile,skiprows=16,usecols={0,1,2},dtype=None,comments="#")
print("\nloaded data:\n", a)

In [ ]:
train_min_brain_weight = np.min(a[0:5,1],axis=0)
train_max_brain_weight = np.max(a[0:5,1],axis=0)
train_avg_brain_weight = np.mean(a[0:5,1],axis=0)
print("training set, brain weight statistics:")
print("Min=",train_min_brain_weight)
print("Max=",train_max_brain_weight)
print("Mean={:.2f}".format(train_avg_brain_weight))

In [ ]:
test_min_body_weight = np.min(a[5:9,2],axis=0)
test_max_body_weight = np.max(a[5:9,2],axis=0)
test_avg_body_weight = np.mean(a[5:9,2],axis=0)
print("test set, body weight statistics:")
print("Min=",test_min_body_weight)
print("Max=",test_max_body_weight)
print("Mean={:.2f}".format(test_avg_body_weight))